name: Test tap-neon

on:
  push:
    branches: [main]
    paths:
    - tap_neon/**
    - tests/**
    - pyproject.toml
    - tox.ini
    - uv.lock
    - .github/workflows/test.yml
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
    - tap_neon/**
    - tests/**
    - pyproject.toml
    - tox.ini
    - uv.lock
    - .github/workflows/test.yml
  schedule:
  - cron: "0 10 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"
  # renovate: datasource=pypi depName=tox
  TOX_VERSION: 4.31.0
  # renovate: datasource=pypi depName=tox-uv
  TOX_UV_VERSION: 1.29.0
  # renovate: datasource=pypi depName=uv
  UV_VERSION: 0.9.4

jobs:
  tests:
    runs-on: ubuntu-24.04
    name: Python ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        python-version:
        - "3.14"
        - "3.13"
        - "3.12"
        - "3.11"
        - "3.10"

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        fetch-depth: 0
    - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      id: setup-python
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
    - uses: astral-sh/setup-uv@2ddd2b9cb38ad8efd50337e8ab201519a34c9f24 # v7.1.1
      with:
        version: ${{ env.UV_VERSION }}
    - name: Run
      env:
        UV_PYTHON: ${{ steps.setup-python.outputs.python-path }}
        TAP_NEON_API_KEY: ${{ secrets.TAP_NEON_API_KEY }}
      run: >
          uvx
          --with tox-uv==${{ env.TOX_UV_VERSION }}
          --with tox==${{ env.TOX_VERSION }}
          tox -e ${{ matrix.python-version }}

  static:
    runs-on: ubuntu-24.04
    name: Static Analysis
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        fetch-depth: 0
    - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      id: setup-python
    - uses: astral-sh/setup-uv@2ddd2b9cb38ad8efd50337e8ab201519a34c9f24 # v7.1.1
      with:
        version: ${{ env.UV_VERSION }}
    - name: Install tools
      env:
        UV_PYTHON: ${{ steps.setup-python.outputs.python-path }}
      run: >
          uv tool install
          --with tox-uv==${{ env.TOX_UV_VERSION }}
          --with tox==${{ env.TOX_VERSION }}
          tox
    - name: Type Checks
      run: tox -e typing
    - name: Dependency Checks
      run: tox -e dependencies
